name: Deploy to Server

on:
  push:
    branches:
      - main  # Скрипт будет срабатывать при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and update
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /root/deploy.sh
